#!/usr/bin/env python3
"""
This script will be called to grade your solution.

The autograder expects this script to:
1. Read in ciphertext as first command line argument.
2. Read in a has_breakpoint flag ("true" or "false") as the second command line
   argument.
3. Print the best guess for the plaintext to stdout.

Example usage:
    ./decode-cli "$(cat data/sample/ciphertext.txt)" false
    ./decode-cli "$(cat data/sample/ciphertext_breakpoint.txt)" true

A default implementation calling decode.py has been provided below.
"""

import sys
from src.decode import decode_no_bp, decode_bp
# from part_1_decode import decode

has_breakpoint = sys.argv[2].lower() == "true"
if has_breakpoint:
    print(decode_bp(sys.argv[1]))
else:
    print(decode_no_bp(sys.argv[1]))

# part1 = sys.argv[2].lower() == "true"
# if part1:
#     print(decode(sys.argv[1], False))
# else:
#     print(fast_decode(sys.argv[1], False))